/* gAi Evaluation Engine v1
 * Holdout generation evaluation for the browser-local language model.
 * Measures reference overlap, keyword hits and answer length.
 * This is a lightweight product metric, not cross-entropy.
 */
import {samples,stats as datasetStats} from './dataset.js';
import {generate,stats as modelStats} from './micro_transformer.js';
const clean=s=>String(s||'').toLowerCase().replace(/[^a-z0-9\s]/g,' ').replace(/\s+/g,' ').trim();
const words=s=>clean(s).split(' ').filter(Boolean),unique=a=>[...new Set(a)];
function score(reference,prediction){const r=unique(words(reference)),p=unique(words(prediction));if(!r.length)return{overlap:0,keywordHit:0};const ps=new Set(p),hits=r.filter(w=>ps.has(w)).length;return{overlap:hits/r.length,keywordHit:hits>=Math.max(1,Math.ceil(Math.min(5,r.length)*.4))?1:0}}
export function evaluate(limit=20){const all=samples();if(!all.length)return{ok:false,reason:'EMPTY_DATASET',dataset:datasetStats(),model:modelStats(),count:0};const shuffled=all.slice().sort(()=>Math.random()-.5),items=shuffled.slice(0,Math.max(1,Math.min(Number(limit)||20,shuffled.length)));let overlap=0,keyword=0,length=0;const examples=items.map(item=>{let prediction='';try{prediction=generate(item.topic,18)}catch{}const s=score(item.text,prediction);overlap+=s.overlap;keyword+=s.keywordHit;length+=words(prediction).length;return{topic:item.topic,expected:item.text,prediction,overlap:Math.round(s.overlap*100),keywordHit:s.keywordHit}});return{ok:true,count:items.length,overlap:overlap/items.length,keywordHit:keyword/items.length,avgLength:length/items.length,examples,dataset:datasetStats(),model:modelStats(),evaluatedAt:new Date().toISOString()}}
function installEvaluationUI(){const install=()=>{if(document.getElementById('evaluationControls'))return;const box=document.getElementById('llmStats');if(!box)return;const wrap=document.createElement('div');wrap.id='evaluationControls';wrap.style.cssText='margin-top:14px;padding:12px;border:1px solid rgba(255,255,255,.1);border-radius:12px';wrap.innerHTML='<div style="font-weight:700;margin-bottom:8px">🧪 Model Evaluation</div><button class="primary mini" id="runEvaluationBtn">📊 Run Validation</button><div id="evaluationSummary" class="muted" style="margin-top:9px">Ready to evaluate dataset samples.</div><div id="evaluationExamples" style="margin-top:8px"></div>';box.parentNode.appendChild(wrap);document.getElementById('runEvaluationBtn').onclick=()=>{const summary=document.getElementById('evaluationSummary'),examples=document.getElementById('evaluationExamples');summary.textContent='Evaluating...';examples.innerHTML='';const r=evaluate(20);if(!r.ok){summary.textContent='⚠ Teach gAi and build a dataset first.';return}summary.innerHTML=`<b>Samples:</b> ${r.count} &nbsp; <b>Reference overlap:</b> ${Math.round(r.overlap*100)}% &nbsp; <b>Keyword hit:</b> ${Math.round(r.keywordHit*100)}% &nbsp; <b>Avg output:</b> ${r.avgLength.toFixed(1)} words`;examples.innerHTML=r.examples.slice(0,3).map((x,i)=>`<div style="margin-top:8px;padding:9px;border-radius:9px;background:rgba(255,255,255,.04)"><b>#${i+1} ${String(x.topic)}</b><br><span class="muted">Expected:</span> ${String(x.expected)}<br><span class="muted">Generated:</span> ${String(x.prediction)||'(empty)'}<br><span class="muted">Overlap:</span> ${x.overlap}%</div>`).join('');localStorage.setItem('gAiEvaluationV1',JSON.stringify(r))}}};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else setTimeout(install,50)}
installEvaluationUI();
export default{evaluate};
