/* gAi Metrics Dashboard v1 */
import {trainingHistory} from './batch_trainer.js';
import {validationHistory} from './validation.js';
import {stats as datasetStats} from './dataset.js';
import {stats as modelStats} from './micro_transformer.js';
function spark(values,label,percent=false){if(!values.length)return `<div class="muted">No ${label} history yet.</div>`;const w=620,h=130,p=12,min=Math.min(...values),max=Math.max(...values),range=max-min||1;const pts=values.map((v,i)=>`${p+i*(w-2*p)/Math.max(1,values.length-1)},${h-p-(v-min)*(h-2*p)/range}`).join(' ');return `<div style="margin-top:10px"><div style="font-weight:600;margin-bottom:4px">${label}</div><svg viewBox="0 0 ${w} ${h}" style="width:100%;height:130px;background:rgba(255,255,255,.025);border-radius:9px"><polyline points="${pts}" fill="none" stroke="currentColor" stroke-width="2"/><circle cx="${w-p}" cy="${h-p-(values.at(-1)-min)*(h-2*p)/range}" r="4" fill="currentColor"/></svg><div class="muted">min ${percent?(min*100).toFixed(1)+'%':min.toFixed(4)} • max ${percent?(max*100).toFixed(1)+'%':max.toFixed(4)} • latest ${percent?(values.at(-1)*100).toFixed(1)+'%':values.at(-1).toFixed(4)}</div></div>`}
function render(){const box=document.getElementById('llmStats');if(!box||document.getElementById('metricsDashboard'))return;const wrap=document.createElement('div');wrap.id='metricsDashboard';wrap.style.cssText='margin-top:14px;padding:12px;border:1px solid rgba(255,255,255,.1);border-radius:12px';wrap.innerHTML='<div style="font-weight:700">📈 Training & Evaluation Metrics</div><div id="metricBody" class="muted" style="margin-top:8px"></div>';box.parentNode.appendChild(wrap);refresh()}
function refresh(){const body=document.getElementById('metricBody');if(!body)return;const th=trainingHistory(),vh=validationHistory(),d=datasetStats(),m=modelStats(),loss=th.map(x=>Number(x.loss)||0),acc=vh.map(x=>Number(x.accuracy)||0);const lastLoss=loss.at(-1),prevLoss=loss.at(-2),lastAcc=acc.at(-1),prevAcc=acc.at(-2);let signal='Not enough history for a trend check.';if(loss.length>1&&acc.length>1){if(lastLoss>prevLoss&&lastAcc<prevAcc)signal='⚠ Possible overfitting/instability: loss rose while validation accuracy fell.';else if(lastLoss<prevLoss&&lastAcc>=prevAcc)signal='✅ Healthy short-term signal: loss fell and validation accuracy held/improved.';else signal='ℹ Mixed trend. Run more training/evaluation cycles before judging.'}body.innerHTML=`<div><b>Dataset:</b> ${d.samples} samples • ${d.topics||0} topics • ${d.epochs} epochs &nbsp; <b>Model:</b> ${m.trainSteps||0} steps</div>${spark(loss,'Training loss')}${spark(acc,'Validation-style accuracy',true)}<div style="margin-top:9px;padding:8px;border-radius:8px;background:rgba(255,255,255,.04)"><b>🧠 Trend:</b> ${signal}</div><button class="primary mini" id="refreshMetricsBtn" style="margin-top:9px">🔄 Refresh Metrics</button>`;document.getElementById('refreshMetricsBtn').onclick=refresh}
if(typeof window!=='undefined'){if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',render,{once:true});else setTimeout(render,900)}
export default{refresh};
