/* gAi Micro Transformer v4
 * Browser-native single-block Transformer experiment.
 * Pipeline: learned subword tokenizer -> dataset text -> Transformer -> Adam.
 * Tiny and educational, not a production LLM.
 */
import {encode,decode,train as trainTokenizer} from './tokenizer.js';
const KEY='gAiMicroTransformerV4';
const CFG={dim:24,heads:4,maxSeq:48,lr:.003,beta1:.9,beta2:.999,eps:1e-8};
const START='<s>',END='</s>';
const clean=s=>String(s||'').replace(/\s+/g,' ').trim();
const tok=s=>encode(clean(s));
const rand=(n,scale=.06)=>Array.from({length:n},()=> (Math.random()*2-1)*scale);
const matrix=(r,c,scale=.06)=>Array.from({length:r},()=>rand(c,scale));
const zeros=(r,c)=>Array.from({length:r},()=>Array(c).fill(0));
const zvec=n=>Array(n).fill(0);
const dot=(a,b)=>{let s=0;for(let i=0;i<a.length;i++)s+=a[i]*b[i];return s};
const add=(a,b)=>a.map((x,i)=>x+b[i]);
const matvec=(M,x)=>M.map(r=>dot(r,x));
const softmax=a=>{const mx=Math.max(...a),e=a.map(x=>Math.exp(Math.max(-30,Math.min(30,x-mx)))),s=e.reduce((a,b)=>a+b,0)||1;return e.map(x=>x/s)};
function norm(x){const mean=x.reduce((a,b)=>a+b,0)/x.length,variance=x.reduce((a,b)=>a+(b-mean)**2,0)/x.length,inv=1/Math.sqrt(variance+1e-5);return{x:x.map(v=>(v-mean)*inv),mean,inv}}
function normBackward(dy,c){const n=dy.length,sum=dy.reduce((a,b)=>a+b,0),sumx=dy.reduce((a,b,i)=>a+b*c.x[i],0);return dy.map((g,i)=>(n*g-sum-c.x[i]*sumx)*c.inv/n)}
function load(){try{return JSON.parse(localStorage.getItem(KEY))||null}catch{return null}}
function save(m){try{localStorage.setItem(KEY,JSON.stringify(m))}catch{}}
function empty(){const d=CFG.dim;return{vocab:[START,END],ids:{[START]:0,[END]:1},E:matrix(2,d),P:matrix(CFG.maxSeq,d),Wq:matrix(d,d),Wk:matrix(d,d),Wv:matrix(d,d),Wo:matrix(d,d),W1:matrix(d*2,d),W2:matrix(d,d*2),b2:rand(d),Wout:matrix(2,d),bout:[0,0],opt:{t:0,state:{}},trainSteps:0,loss:0}}
function ensure(){let m=load();if(!m||!m.E||!m.Wq||!m.W1||!m.Wout)m=empty();if(!m.P||m.P.length!==CFG.maxSeq)m.P=matrix(CFG.maxSeq,CFG.dim);if(!m.W1||m.W1.length!==CFG.dim*2)m.W1=matrix(CFG.dim*2,CFG.dim);if(!m.W2||m.W2.length!==CFG.dim)m.W2=matrix(CFG.dim,CFG.dim*2);if(!m.b2||m.b2.length!==CFG.dim)m.b2=rand(CFG.dim);if(!m.opt)m.opt={t:0,state:{}};if(!m.opt.state)m.opt.state={};save(m);return m}
function resize(m){while(m.E.length<m.vocab.length)m.E.push(rand(CFG.dim));while(m.Wout.length<m.vocab.length)m.Wout.push(rand(CFG.dim));while(m.bout.length<m.vocab.length)m.bout.push(0)}
function addVocab(m,tokens){for(const t of tokens)if(!(t in m.ids)){m.ids[t]=m.vocab.length;m.vocab.push(t)}resize(m)}
function forward(m,ids){const d=CFG.dim,h=CFG.heads,hd=d/h,n=ids.length,x=ids.map((id,i)=>add(m.E[id],m.P[i])),Q=x.map(v=>matvec(m.Wq,v)),K=x.map(v=>matvec(m.Wk,v)),V=x.map(v=>matvec(m.Wv,v)),probs=Array.from({length:h},()=>Array(n)),ctx=Array.from({length:n},()=>zvec(d));for(let head=0;head<h;head++){const off=head*hd;for(let i=0;i<n;i++){const scores=[];for(let j=0;j<=i;j++)scores.push(dot(Q[i].slice(off,off+hd),K[j].slice(off,off+hd))/Math.sqrt(hd));probs[head][i]=softmax(scores);for(let j=0;j<=i;j++)for(let k=0;k<hd;k++)ctx[i][off+k]+=probs[head][i][j]*V[j][off+k]}}const a=ctx.map((c,i)=>add(x[i],matvec(m.Wo,c))),ln=a.map(norm),ffpre=ln.map(o=>matvec(m.W1,o)),ff=ffpre.map(v=>v.map(q=>Math.max(0,q))),hidden=ln.map((o,i)=>add(o,matvec(m.W2,ff[i])).map((v,j)=>v+m.b2[j])),last=hidden[n-1]||zvec(d);return{ids,x,Q,K,V,probs,ctx,a,ln,ffpre,ff,hidden,last,logits:add(matvec(m.Wout,last),m.bout)}}
function gradients(m,f,target){const d=CFG.dim,h=CFG.heads,hd=d/h,n=f.ids.length,g={E:zeros(m.E.length,d),P:zeros(CFG.maxSeq,d),Wq:zeros(d,d),Wk:zeros(d,d),Wv:zeros(d,d),Wo:zeros(d,d),W1:zeros(d*2,d),W2:zeros(d,d*2),b2:zvec(d),Wout:zeros(m.vocab.length,d),bout:zvec(m.vocab.length)};const p=softmax(f.logits),dl=p.slice();dl[target]-=1;const dh=Array.from({length:n},()=>zvec(d));for(let r=0;r<m.vocab.length;r++){g.bout[r]+=dl[r];for(let j=0;j<d;j++){g.Wout[r][j]+=dl[r]*f.last[j];dh[n-1][j]+=dl[r]*m.Wout[r][j]}}
const dln=Array.from({length:n},()=>zvec(d));for(let i=0;i<n;i++){const dff=zvec(d*2);for(let j=0;j<d;j++){g.b2[j]+=dh[i][j];for(let k=0;k<d*2;k++)g.W2[j][k]+=dh[i][j]*f.ff[i][k]}for(let k=0;k<d*2;k++){let u=0;for(let j=0;j<d;j++)u+=m.W2[j][k]*dh[i][j];dff[k]=f.ffpre[i][k]>0?u:0;for(let j=0;j<d;j++)g.W1[k][j]+=dff[k]*f.ln[i].x[j]}for(let j=0;j<d;j++){for(let k=0;k<d*2;k++)dln[i][j]+=m.W1[k][j]*dff[k];dln[i][j]+=dh[i][j]}}
const da=dln.map((v,i)=>normBackward(v,f.ln[i])),dx=da.map(v=>v.slice()),dctx=Array.from({length:n},()=>zvec(d));for(let i=0;i<n;i++){for(let r=0;r<d;r++)for(let c=0;c<d;c++)g.Wo[r][c]+=da[i][r]*f.ctx[i][c];dctx[i]=matvec(m.Wo,da[i])}
for(let head=0;head<h;head++){const off=head*hd,scale=Math.sqrt(hd);for(let i=0;i<n;i++){const pp=f.probs[head][i],dp=zvec(i+1),ds=zvec(i+1);for(let j=0;j<=i;j++)for(let k=0;k<hd;k++)dp[j]+=dctx[i][off+k]*f.V[j][off+k];const mean=pp.reduce((s,v,j)=>s+v*dp[j],0);for(let j=0;j<=i;j++){ds[j]=pp[j]*(dp[j]-mean);for(let k=0;k<hd;k++){const row=off+k;g.Wv[row].forEach((_,c)=>g.Wv[row][c]+=dctx[i][row]*pp[j]*f.x[j][c]);const fac=ds[j]/scale;for(let c=0;c<d;c++){g.Wq[row][c]+=fac*f.K[j][row]*f.x[i][c];g.Wk[row][c]+=fac*f.Q[i][row]*f.x[j][c];dx[i][c]+=fac*f.K[j][row]*m.Wq[row][c];dx[j][c]+=fac*f.Q[i][row]*m.Wk[row][c]}}for(let k=0;k<hd;k++){const row=off+k;for(let c=0;c<d;c++)dx[j][c]+=dctx[i][row]*pp[j]*m.Wv[row][c]}}}}
for(let i=0;i<n;i++)for(let j=0;j<d;j++){g.E[f.ids[i]][j]+=dx[i][j];g.P[i][j]+=dx[i][j]}return g}
function adam(m,g){const o=m.opt,t=++o.t,b1=CFG.beta1,b2=CFG.beta2,lr=CFG.lr,clip=.5;const apply=(name,p,gr)=>{let s=o.state[name];if(!s)s=o.state[name]={m:{},v:{}};const one=(k,x,z)=>{z=Math.max(-clip,Math.min(clip,z));s.m[k]=b1*(s.m[k]??0)+(1-b1)*z;s.v[k]=b2*(s.v[k]??0)+(1-b2)*z*z;const mh=s.m[k]/(1-b1**t),vh=s.v[k]/(1-b2**t);return x-lr*mh/(Math.sqrt(vh)+CFG.eps)};if(Array.isArray(p[0]))for(let i=0;i<p.length;i++)for(let j=0;j<p[i].length;j++)p[i][j]=one(i+'_'+j,p[i][j],gr[i][j]);else for(let i=0;i<p.length;i++)p[i]=one(String(i),p[i],gr[i])};for(const k of ['E','P','Wq','Wk','Wv','Wo','W1','W2','b2','Wout','bout'])apply(k,m[k],g[k])}
function step(m,text){const tokens=[START,...tok(text),END].slice(0,CFG.maxSeq);addVocab(m,tokens);let loss=0,steps=0;for(let i=1;i<tokens.length;i++){const input=tokens.slice(Math.max(0,i-12),i),target=m.ids[tokens[i]],f=forward(m,input.map(t=>m.ids[t])),pr=softmax(f.logits);loss-=Math.log(Math.max(1e-8,pr[target]||1e-8));adam(m,gradients(m,f,target));steps++}m.trainSteps+=steps;m.loss=steps?loss/steps:m.loss;return{loss:m.loss,steps}}
export function train(text,epochs=1){const raw=clean(text);trainTokenizer(raw,24);const m=ensure();const pieces=raw.split(/[.!?\n]+/).map(clean).filter(Boolean);let loss=0,steps=0;for(let e=0;e<epochs;e++)for(const s of pieces){const r=step(m,s);loss+=r.loss;steps+=r.steps}save(m);return{loss:steps?loss/steps:0,steps,vocab:m.vocab.length,trainSteps:m.trainSteps}}
export function trainFromLessons(lessons=[]){let corpus=lessons.map(l=>`${l.topic}. ${l.content}`).join('\n');return corpus?train(corpus,1):{loss:0,steps:0,vocab:ensure().vocab.length,trainSteps:ensure().trainSteps}}
export function generate(prompt='',maxTokens=24){const m=ensure();const ctx=tok(prompt).slice(-12);let ids=ctx.length?ctx.map(t=>m.ids[t]??m.ids[START]):[m.ids[START]],out=[];for(let i=0;i<maxTokens;i++){const f=forward(m,ids),p=softmax(f.logits),rank=p.map((v,id)=>({v,id})).filter(x=>x.id>1).sort((a,b)=>b.v-a.v).slice(0,Math.min(6,m.vocab.length-2));if(!rank.length)break;let r=Math.random()*(rank.reduce((a,x)=>a+x.v,0)||1),chosen=rank[0].id;for(const x of rank){r-=x.v;if(r<=0){chosen=x.id;break}}const t=m.vocab[chosen];if(t===END)break;out.push(t);ids=[...ids,chosen].slice(-12)}return decode(out)}
export function inspect(prompt=''){const m=ensure(),tokens=tok(prompt).slice(-12),ids=tokens.length?tokens.map(t=>m.ids[t]??m.ids[START]):[m.ids[START]],f=forward(m,ids);return{architecture:{embedding:CFG.dim,heads:CFG.heads,context:CFG.maxSeq},tokens,embedding:f.last.slice(0,8),attentionEnergy:f.last.reduce((a,b)=>a+Math.abs(b),0)/f.last.length,logits:f.logits}}
export function stats(){const m=ensure();return{vocabulary:m.vocab.length,embedding:CFG.dim,heads:CFG.heads,context:CFG.maxSeq,trainSteps:m.trainSteps||0,loss:m.loss||0,optimizer:'Adam',backprop:true,fullBackprop:true,tokenizer:'Subword BPE-style',layers:['Q','K','V','attention','O','layernorm','FFN','embeddings','LM head']}}
export function resetModel(){try{localStorage.removeItem(KEY)}catch{}}
export default{train,trainFromLessons,generate,inspect,stats,resetModel};