/* gAi Micro Transformer v5
 * Browser-native single-block Transformer experiment.
 * Pipeline: learned subword tokenizer -> dataset text -> Transformer -> Adam -> checkpoint.
 * Tiny and educational, not a production LLM.
 */
import {encode,decode,train as trainTokenizer} from './tokenizer.js';
const KEY='gAiMicroTransformerV5',CKEY='gAiMicroTransformerCheckpointV1';
const CFG={dim:24,heads:4,maxSeq:48,lr:.003,minLR:.0003,warmup:25,beta1:.9,beta2:.999,eps:1e-8,clip:1.0};
const START='<s>',END='</s>';
const clean=s=>String(s||'').replace(/\s+/g,' ').trim(); const tok=s=>encode(clean(s));
const rand=(n,scale=.06)=>Array.from({length:n},()=> (Math.random()*2-1)*scale),matrix=(r,c,scale=.06)=>Array.from({length:r},()=>rand(c,scale)),zeros=(r,c)=>Array.from({length:r},()=>Array(c).fill(0)),zvec=n=>Array(n).fill(0);
const dot=(a,b)=>{let s=0;for(let i=0;i<a.length;i++)s+=a[i]*b[i];return s}; const matvec=(M,x)=>M.map(r=>dot(r,x));
const add=(a,b)=>a.map((x,i)=>x+b[i]); const softmax=a=>{const mx=Math.max(...a),e=a.map(x=>Math.exp(Math.max(-30,Math.min(30,x-mx)))),s=e.reduce((a,b)=>a+b,0)||1;return e.map(x=>x/s)};
function norm(x){const mean=x.reduce((a,b)=>a+b,0)/x.length,variance=x.reduce((a,b)=>a+(b-mean)**2,0)/x.length,inv=1/Math.sqrt(variance+1e-5);return{x:x.map(v=>(v-mean)*inv),mean,inv}}
function normBackward(dy,c){const n=dy.length,sum=dy.reduce((a,b)=>a+b,0),sumx=dy.reduce((a,b,i)=>a+b*c.x[i],0);return dy.map((g,i)=>(n*g-sum-c.x[i]*sumx)*c.inv/n)}
function load(){try{return JSON.parse(localStorage.getItem(KEY))||null}catch{return null}} function save(m){try{localStorage.setItem(KEY,JSON.stringify(m))}catch{}}
function empty(){const d=CFG.dim;return{version:5,vocab:[START,END],ids:{[START]:0,[END]:1},E:matrix(2,d),P:matrix(CFG.maxSeq,d),Wq:matrix(d,d),Wk:matrix(d,d),Wv:matrix(d,d),Wo:matrix(d,d),W1:matrix(d*2,d),W2:matrix(d,d*2),b2:rand(d),Wout:matrix(2,d),bout:[0,0],opt:{t:0,state:{}},trainSteps:0,loss:0}}
function ensure(){let m=load();if(!m||!m.E||!m.Wq||!m.W1||!m.Wout)m=empty();if(!m.P||m.P.length!==CFG.maxSeq)m.P=matrix(CFG.maxSeq,CFG.dim);if(!m.W1||m.W1.length!==CFG.dim*2)m.W1=matrix(CFG.dim*2,CFG.dim);if(!m.W2||m.W2.length!==CFG.dim)m.W2=matrix(CFG.dim,CFG.dim*2);if(!m.b2||m.b2.length!==CFG.dim)m.b2=rand(CFG.dim);if(!m.opt)m.opt={t:0,state:{}};if(!m.opt.state)m.opt.state={};save(m);return m}
function resize(m){while(m.E.length<m.vocab.length)m.E.push(rand(CFG.dim));while(m.Wout.length<m.vocab.length)m.Wout.push(rand(CFG.dim));while(m.bout.length<m.vocab.length)m.bout.push(0)}
function addVocab(m,tokens){for(const t of tokens)if(!(t in m.ids)){m.ids[t]=m.vocab.length;m.vocab.push(t)}resize(m)}
function forward(m,ids){const d=CFG.dim,h=CFG.heads,hd=d/h,n=ids.length,x=ids.map((id,i)=>add(m.E[id],m.P[i])),Q=x.map(v=>matvec(m.Wq,v)),K=x.map(v=>matvec(m.Wk,v)),V=x.map(v=>matvec(m.Wv,v)),probs=Array.from({length:h},()=>Array(n)),ctx=Array.from({length:n},()=>zvec(d));for(let head=0;head<h;head++){const off=head*hd;for(let i=0;i<n;i++){const scores=[];for(let j=0;j<=i;j++)scores.push(dot(Q[i].slice(off,off+hd),K[j].slice(off,off+hd))/Math.sqrt(hd));probs[head][i]=softmax(scores);for(let j=0;j<=i;j++)for(let k=0;k<hd;k++)ctx[i][off+k]+=probs[head][i][j]*V[j][off+k]}}const a=ctx.map((c,i)=>add(x[i],matvec(m.Wo,c))),ln=a.map(norm),ffpre=ln.map(o=>matvec(m.W1,o)),ff=ffpre.map(v=>v.map(q=>Math.max(0,q))),hidden=ln.map((o,i)=>add(o,matvec(m.W2,ff[i])).map((v,j)=>v+m.b2[j])),last=hidden[n-1]||zvec(d);return{ids,x,Q,K,V,probs,ctx,a,ln,ffpre,ff,hidden,last,logits:add(matvec(m.Wout,last),m.bout)}}
function gradients(m,f,target){const d=CFG.dim,h=CFG.heads,hd=d/h,n=f.ids.length,g={E:zeros(m.E.length,d),P:zeros(CFG.maxSeq,d),Wq:zeros(d,d),Wk:zeros(d,d),Wv:zeros(d,d),Wo:zeros(d,d),W1:zeros(d*2,d),W2:zeros(d,d*2),b2:zvec(d),Wout:zeros(m.vocab.length,d),bout:zvec(m.vocab.length)};const p=softmax(f.logits),dl=p.slice();dl[target]-=1;const dh=Array.from({length:n},()=>zvec(d));for(let r=0;r<m.vocab.length;r++){g.bout[r]+=dl[r];for(let j=0;j<d;j++){g.Wout[r][j]+=dl[r]*f.last[j];dh[n-1][j]+=dl[r]*m.Wout[r][j]}}const dln=Array.from({length:n},()=>zvec(d));for(let i=0;i<n;i++){const dff=zvec(d*2);for(let j=0;j<d;j++){g.b2[j]+=dh[i][j];for(let k=0;k<d*2;k++)g.W2[j][k]+=dh[i][j]*f.ff[i][k]}for(let k=0;k<d*2;k++){let u=0;for(let j=0;j<d;j++)u+=m.W2[j][k]*dh[i][j];dff[k]=f.ffpre[i][k]>0?u:0;for(let j=0;j<d;j++)g.W1[k][j]+=dff[k]*f.ln[i].x[j]}for(let j=0;j<d;j++){for(let k=0;k<d*2;k++)dln[i][j]+=m.W1[k][j]*dff[k];dln[i][j]+=dh[i][j]}}const da=dln.map((v,i)=>normBackward(v,f.ln[i])),dx=da.map(v=>v.slice()),dctx=Array.from({length:n},()=>zvec(d));for(let i=0;i<n;i++){for(let r=0;r<d;r++)for(let c=0;c<d;c++)g.Wo[r][c]+=da[i][r]*f.ctx[i][c];dctx[i]=matvec(m.Wo,da[i])}for(let head=0;head<h;head++){const off=head*hd,scale=Math.sqrt(hd);for(let i=0;i<n;i++){const pp=f.probs[head][i],dp=zvec(i+1),ds=zvec(i+1);for(let j=0;j<=i;j++)for(let k=0;k<hd;k++)dp[j]+=dctx[i][off+k]*f.V[j][off+k];const mean=pp.reduce((s,v,j)=>s+v*dp[j],0);for(let j=0;j<=i;j++){ds[j]=pp[j]*(dp[j]-mean);for(let k=0;k<hd;k++){const row=off+k;for(let c=0;c<d;c++){g.Wv[row][c]+=dctx[i][row]*pp[j]*f.x[j][c];const fac=ds[j]/scale;g.Wq[row][c]+=fac*f.K[j][row]*f.x[i][c];g.Wk[row][c]+=fac*f.Q[i][row]*f.x[j][c];dx[i][c]+=fac*f.K[j][row]*m.Wq[row][c];dx[j][c]+=fac*f.Q[i][row]*m.Wk[row][c];dx[j][c]+=dctx[i][row]*pp[j]*m.Wv[row][c]}}}}}for(let i=0;i<n;i++)for(let j=0;j<d;j++){g.E[f.ids[i]][j]+=dx[i][j];g.P[i][j]+=dx[i][j]}return g}
function gradNorm(g){let s=0;for(const v of Object.values(g)){if(Array.isArray(v[0]))for(const row of v)for(const x of row)if(Number.isFinite(x))s+=x*x;else for(const x of v)if(Number.isFinite(x))s+=x*x}return Math.sqrt(s)}
function adam(m,g){const o=m.opt,t=++o.t,b1=CFG.beta1,b2=CFG.beta2,base=CFG.lr,lr=Math.max(CFG.minLR,base*(t<CFG.warmup?t/CFG.warmup:Math.pow(.98,Math.floor((t-CFG.warmup)/50)))),clip=CFG.clip,gn=gradNorm(g),scale=Number.isFinite(gn)&&gn>clip?clip/gn:1;o.lastGradNorm=Number.isFinite(gn)?gn:0;o.lastLR=lr;const apply=(name,p,gr)=>{let s=o.state[name];if(!s)s=o.state[name]={m:{},v:{}};const one=(k,x,z)=>{z=(Number.isFinite(z)?z:0)*scale;z=Math.max(-clip,Math.min(clip,z));s.m[k]=b1*(s.m[k]??0)+(1-b1)*z;s.v[k]=b2*(s.v[k]??0)+(1-b2)*z*z;const y=x-lr*(s.m[k]/(1-b1**t))/(Math.sqrt(s.v[k]/(1-b2**t))+CFG.eps);return Number.isFinite(y)?y:x};if(Array.isArray(p[0]))for(let i=0;i<p.length;i++)for(let j=0;j<p[i].length;j++)p[i][j]=one(i+'_'+j,p[i][j],gr[i][j]);else for(let i=0;i<p.length;i++)p[i]=one(String(i),p[i],gr[i])};for(const k of ['E','P','Wq','Wk','Wv','Wo','W1','W2','b2','Wout','bout'])apply(k,m[k],g[k])}
function step(m,text){const tokens=[START,...tok(text),END].slice(0,CFG.maxSeq);addVocab(m,tokens);let loss=0,steps=0;for(let i=1;i<tokens.length;i++){const input=tokens.slice(Math.max(0,i-12),i),target=m.ids[tokens[i]],f=forward(m,input.map(t=>m.ids[t])),pr=softmax(f.logits);if(!Number.isFinite(pr[target]))continue;const sampleLoss=-Math.log(Math.max(1e-8,pr[target]||1e-8));if(!Number.isFinite(sampleLoss))continue;loss+=sampleLoss;adam(m,gradients(m,f,target));steps++}m.trainSteps+=steps;m.loss=steps?loss/steps:m.loss;return{loss:m.loss,steps}}
export function train(text,epochs=1){const raw=clean(text);if(!raw)return{loss:0,steps:0,vocab:ensure().vocab.length,trainSteps:ensure().trainSteps};trainTokenizer(raw,24);const m=ensure(),pieces=raw.split(/[.!?\n]+/).map(clean).filter(Boolean);let loss=0,steps=0;for(let e=0;e<epochs;e++)for(const s of pieces){const r=step(m,s);loss+=r.loss;steps+=r.steps}save(m);checkpoint('auto');return{loss:steps?loss/steps:0,steps,vocab:m.vocab.length,trainSteps:m.trainSteps}}
export function trainFromLessons(lessons=[]){const corpus=lessons.map(l=>`${l.topic}. ${l.content}`).join('\n');return corpus?train(corpus,1):{loss:0,steps:0,vocab:ensure().vocab.length,trainSteps:ensure().trainSteps}}
export function generate(prompt='',maxTokens=24){const m=ensure(),ctx=tok(prompt).slice(-12);let ids=ctx.length?ctx.map(t=>m.ids[t]??m.ids[START]):[m.ids[START]],out=[];for(let i=0;i<maxTokens;i++){const f=forward(m,ids),p=softmax(f.logits),rank=p.map((v,id)=>({v,id})).filter(x=>x.id>1).sort((a,b)=>b.v-a.v).slice(0,Math.min(6,m.vocab.length-2));if(!rank.length)break;let r=Math.random()*(rank.reduce((a,x)=>a+x.v,0)||1),chosen=rank[0].id;for(const x of rank){r-=x.v;if(r<=0){chosen=x.id;break}}const t=m.vocab[chosen];if(t===END)break;out.push(t);ids=[...ids,chosen].slice(-12)}return decode(out)}
export function inspect(prompt=''){const m=ensure(),tokens=tok(prompt).slice(-12),ids=tokens.length?tokens.map(t=>m.ids[t]??m.ids[START]):[m.ids[START]],f=forward(m,ids);return{architecture:{embedding:CFG.dim,heads:CFG.heads,context:CFG.maxSeq},tokens,embedding:f.last.slice(0,8),attentionEnergy:f.last.reduce((a,b)=>a+Math.abs(b),0)/f.last.length,logits:f.logits}}
export function stats(){const m=ensure();return{version:5,vocabulary:m.vocab.length,embedding:CFG.dim,heads:CFG.heads,context:CFG.maxSeq,trainSteps:m.trainSteps||0,loss:m.loss||0,optimizer:'Adam',backprop:true,fullBackprop:true,tokenizer:'Subword BPE-style',checkpoint:!!loadCheckpoint(),checkpointSteps:loadCheckpoint()?.trainSteps||0,gradNorm:m.opt?.lastGradNorm||0,learningRate:m.opt?.lastLR||CFG.lr,gradientClipping:true,lrSchedule:'warmup + decay',layers:['Q','K','V','attention','O','layernorm','FFN','embeddings','LM head']}}
function checkpointPayload(m){return{version:5,savedAt:new Date().toISOString(),trainSteps:m.trainSteps,loss:m.loss,vocab:m.vocab,ids:m.ids,E:m.E,P:m.P,Wq:m.Wq,Wk:m.Wk,Wv:m.Wv,Wo:m.Wo,W1:m.W1,W2:m.W2,b2:m.b2,Wout:m.Wout,bout:m.bout,opt:m.opt}}
export function checkpoint(label='manual'){const m=ensure();try{localStorage.setItem(CKEY,JSON.stringify({...checkpointPayload(m),label}));return{ok:true,label,trainSteps:m.trainSteps,savedAt:new Date().toISOString()}}catch{return{ok:false,label}}}
function loadCheckpoint(){try{return JSON.parse(localStorage.getItem(CKEY))||null}catch{return null}}
export function restoreCheckpoint(){const c=loadCheckpoint();if(!c)return{ok:false,reason:'NO_CHECKPOINT'};try{localStorage.setItem(KEY,JSON.stringify(c));return{ok:true,trainSteps:c.trainSteps,loss:c.loss,savedAt:c.savedAt}}catch{return{ok:false,reason:'RESTORE_FAILED'}}}
export function checkpointInfo(){const c=loadCheckpoint();return c?{exists:true,label:c.label||'checkpoint',savedAt:c.savedAt,trainSteps:c.trainSteps||0,loss:c.loss||0,vocab:c.vocab?.length||0}:{exists:false}}
export function resetModel(){try{localStorage.removeItem(KEY)}catch{}}
export function resetCheckpoint(){try{localStorage.removeItem(CKEY)}catch{}}
export default{train,trainFromLessons,generate,inspect,stats,checkpoint,restoreCheckpoint,checkpointInfo,resetModel,resetCheckpoint};

/* UI bridge: keeps the existing page compatible while exposing v5 checkpoint controls. */
function installV5UI(){
  const patch=()=>{
    const statsBox=document.getElementById('llmStats');
    if(statsBox && !document.getElementById('checkpointControls')){
      const wrap=document.createElement('div');
      wrap.id='checkpointControls';
      wrap.style.cssText='display:flex;gap:8px;flex-wrap:wrap;margin-top:12px';
      wrap.innerHTML='<button class="primary mini" id="saveCheckpointBtn">💾 Save Checkpoint</button><button class="primary mini" id="restoreCheckpointBtn">↩ Restore</button><button class="primary mini" id="resetCheckpointBtn">🗑 Reset</button><span id="checkpointStatus" class="muted" style="align-self:center"></span>';
      statsBox.parentNode.appendChild(wrap);
      document.getElementById('saveCheckpointBtn').onclick=()=>{const r=checkpoint('manual');document.getElementById('checkpointStatus').textContent=r.ok?`✓ Saved at step ${r.trainSteps}`:'✕ Save failed';renderV5Stats()};
      document.getElementById('restoreCheckpointBtn').onclick=()=>{const r=restoreCheckpoint();document.getElementById('checkpointStatus').textContent=r.ok?`✓ Restored step ${r.trainSteps}`:'⚠ No checkpoint';renderV5Stats()};
      document.getElementById('resetCheckpointBtn').onclick=()=>{resetCheckpoint();document.getElementById('checkpointStatus').textContent='✓ Checkpoint deleted';renderV5Stats()};
    }
    const percent=document.getElementById('llmPercent'),bar=document.getElementById('llmBar'),steps=document.getElementById('llmSteps');
    if(percent)percent.textContent='90%'; if(bar)bar.style.width='90%';
    if(steps){steps.innerHTML=['Tokenizer','Vocabulary','Embeddings','Positional encoding','Causal self-attention','Feed-forward block','Backpropagation','Adam optimizer','Full Transformer backprop','Better tokenizer','Dataset pipeline','Checkpoint / inference pipeline','Gradient clipping','Learning-rate warmup + decay','NaN/Inf training guards','Large dataset training'].map((x,i)=>`<span class="${i<15?'done':'next'}">${i<15?'✓':'○'} ${x}</span>`).join('')}
    document.querySelectorAll('*').forEach(el=>{if(el.children.length===0&&el.textContent.trim()==='Micro Transformer v4')el.textContent='Micro Transformer v5'});
    renderV5Stats();
  };
  const renderV5Stats=()=>{const box=document.getElementById('llmStats');if(!box)return;const s=stats(),c=checkpointInfo();box.innerHTML=`Transformer: <b>v5</b> • vocab ${s.vocabulary} • train steps ${s.trainSteps} • loss ${Number(s.loss||0).toFixed(3)} • optimizer ${s.optimizer}<br>Stability: <b>clip ${s.gradientClipping?'ON':'OFF'}</b> • lr ${Number(s.learningRate||0).toFixed(5)} • grad ${Number(s.gradNorm||0).toFixed(3)}<br>Tokenizer: <b>${window.gAiTokenizer?.stats?.().merges||0}</b> learned merges • checkpoint: <b>${c.exists?'READY':'none'}</b>${c.exists?` • saved step ${c.trainSteps}`:''}`;};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',patch);else patch();
  window.addEventListener('gAiTrainingComplete',renderV5Stats);
}
installV5UI();