/* gAi Model Health v2
 * Final integration gate for local LLM readiness.
 */
import {stats as modelStats} from './micro_transformer.js';
import {stats as datasetStats} from './dataset.js';
import {history as evalHistory} from './production_eval.js';
import {validationHistory} from './validation.js';
const KEY='gAiHealthV2';
function snapshot(){const m=modelStats(),d=datasetStats(),e=evalHistory(),v=validationHistory();const lastV=v.length?v.at(-1):null;return{time:Date.now(),steps:m.trainSteps||0,loss:Number(m.loss)||0,samples:d.samples||0,trainSamples:d.train||0,validationSamples:d.validation||0,epochs:d.epochs||0,eval:e.length?e.at(-1).score:null,validation:lastV?Number(lastV.accuracy)||0:null,checkpoint:!!m.checkpoint,inference:typeof m.inference==='object'||!!m.inferenceConfig}}
export function health(){const h=snapshot();try{localStorage.setItem(KEY,JSON.stringify(h))}catch{}return h}
export function readiness(){const h=health();const checks={dataset:h.samples>=10,training:h.trainSamples>=8,steps:h.steps>=10,lossFinite:Number.isFinite(h.loss),validationSamples:h.validationSamples>=1,validationRun:h.validation!==null,checkpoint:h.checkpoint,inference:h.inference};return{...h,checks,ready:Object.values(checks).every(Boolean),progress:Object.values(checks).filter(Boolean).length/Object.keys(checks).length*100}}
function install(){if(typeof document==='undefined')return;const box=document.getElementById('llmStats');if(!box||document.getElementById('modelHealth'))return;const w=document.createElement('div');w.id='modelHealth';w.style.cssText='margin-top:14px;padding:12px;border-top:1px solid rgba(255,255,255,.1)';w.innerHTML='<div style="font-weight:700">🩺 Final LLM Readiness</div><div id="healthText" class="muted" style="margin-top:6px"></div><div style="height:7px;background:rgba(255,255,255,.08);border-radius:9px;overflow:hidden;margin-top:8px"><div id="healthBar" style="height:100%;width:0%;transition:width .25s"></div></div><button class="primary mini" id="healthBtn" style="margin-top:8px">🔄 Run Final Check</button>';box.parentNode.appendChild(w);const render=()=>{const r=readiness(),pct=Math.round(r.progress);document.getElementById('healthBar').style.width=pct+'%';document.getElementById('healthText').textContent=`${r.ready?'🟢 100% Integrated':'🟡 '+pct+'% Ready'} • dataset ${r.samples} • train ${r.trainSamples} • validation ${r.validationSamples} • steps ${r.steps} • loss ${r.loss.toFixed(4)}`;const nodes=[...document.querySelectorAll('[id*="llm"], [id*="LLM"], [class*="llm"]')];for(const n of nodes){const t=n.textContent||'';if(/LLM_PROGRESS|LLM progress|%/.test(t)&&n.children.length===0)n.textContent=t.replace(/(?:65|70|75|80|85|90|95|100)%/g,pct+'%')}};document.getElementById('healthBtn').onclick=render;render()}
if(typeof window!=='undefined'){Promise.all([import('./production_eval.js'),import('./validation.js')]).then(()=>{if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else setTimeout(install,1400)}).catch(()=>{})}
export default{health,readiness};
