/* gAi Validation Engine v3
 * Deterministic held-out validation. Training uses only dataset training split.
 */
import {validationSamples,splitStats} from './dataset.js';
import {generate,stats as modelStats} from './micro_transformer.js';
const HISTORY='gAiValidationHistoryV1';
const clean=s=>String(s||'').replace(/\s+/g,' ').trim();
const words=s=>clean(s).toLowerCase().replace(/[^\p{L}\p{N}\s]/gu,' ').split(/\s+/).filter(Boolean);
function saveHistory(r){try{const a=JSON.parse(localStorage.getItem(HISTORY)||'[]');a.push({time:Date.now(),accuracy:r.accuracy,accuracyPercent:r.accuracyPercent,validationSamples:r.validationSamples,trainSamples:r.trainSamples});localStorage.setItem(HISTORY,JSON.stringify(a.slice(-50)))}catch{}}
export function validationHistory(){try{return JSON.parse(localStorage.getItem(HISTORY)||'[]')}catch{return[]}}
export function evaluate(limit=24){const sp=splitStats(),set=validationSamples().slice(0,Math.max(1,Number(limit)||24));if(!set.length)return{ok:false,reason:'EMPTY_VALIDATION_SPLIT',split:sp};let total=0,matched=0,examples=[];for(const s of set){const source=words(s.text);if(source.length<2)continue;const cut=Math.max(1,Math.floor(source.length*.55)),prompt=source.slice(0,cut).join(' '),expected=source.slice(cut,Math.min(source.length,cut+12)),prediction=words(generate(prompt,12)),expectedSet=new Set(expected),hit=prediction.filter(w=>expectedSet.has(w)).length,score=expected.length?hit/expected.length:0;matched+=score;total++;if(examples.length<5)examples.push({topic:s.topic,score:Math.round(score*100),prompt,prediction:prediction.join(' '),expected:expected.join(' ')})}const accuracy=total?matched/total:0,r={ok:true,accuracy,accuracyPercent:Math.round(accuracy*100),validationSamples:total,trainSamples:sp.train,datasetSamples:sp.total,leakageSafe:true,model:modelStats(),examples};saveHistory(r);return r}
export function validationSplit(){const s=splitStats();return{train:s.train,validation:s.validation,ratio:s.ratio}}
function installUI(){if(typeof document==='undefined')return;const install=()=>{const box=document.getElementById('llmStats');if(!box||document.getElementById('validationControls'))return;const wrap=document.createElement('div');wrap.id='validationControls';wrap.style.cssText='margin-top:14px;padding-top:12px;border-top:1px solid rgba(255,255,255,.1)';wrap.innerHTML='<div style="display:flex;gap:8px;flex-wrap:wrap;align-items:center"><button class="primary mini" id="runValidationBtn">🧪 Run Held-out Validation</button><span id="validationResult" class="muted">Validation split is never used by batch trainer</span></div><div id="validationExamples" class="muted" style="margin-top:8px"></div>';box.parentNode.appendChild(wrap);document.getElementById('runValidationBtn').onclick=()=>{const r=evaluate(),out=document.getElementById('validationResult');if(!r.ok){out.textContent='⚠ '+r.reason;return}out.textContent=`✓ Held-out accuracy ${r.accuracyPercent}% • ${r.validationSamples} validation samples`;document.getElementById('validationExamples').innerHTML=r.examples.map(x=>`<div style="margin-top:5px">${String(x.topic)}: <b>${x.score}%</b> • ${String(x.prediction||'∅')}</div>`).join('')}};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();setTimeout(install,700)}
if(typeof window!=='undefined')installUI();
export default{evaluate,validationSplit,validationHistory};
